Add USDC
onbloc/gno-token-resource pull request #13
Opened 2024-05-15 12:10 UTC by adr-sk

Adding USD Coin (USDC) `gno.land/r/demo/usdc` .

This is a GRC-20 token to be treated as a stablecoin in testnets, issued only for testing purposes.

2024-05-24 06:18 UTC, r3v4s requested changes
add usdc data in `portal-loop.json` too.

2024-05-27 05:58 UTC, jinoosss reviewed
Just fix the indentation.

2024-05-27 05:58 UTC, jinoosss commented on grc20/assets.json
> +}
Check the indentation. 

```suggestion
    "name": "Usd Coin",
    "pkg_path": "gno.land/r/demo/usdc",
    "symbol": "USDC",
    "decimals": 6,
    "description": "USDC is a GRC20 stablecoin issued solely for testing purposes.",
    "website_url": "https://beta.gnoswap.io",
    "image": "/grc20/images/gno_land_r_demo_usdc.svg"
  }
```

2024-05-27 05:58 UTC, jinoosss commented on grc20/portal-loop.json
> +  "image": "/grc20/images/gno_land_r_demo_usdc.svg"
Check the indentation. 

```suggestion
    "name": "Usd Coin",
    "pkg_path": "gno.land/r/demo/usdc",
    "symbol": "USDC",
    "decimals": 6,
    "chain_id": "portal-loop",
    "description": "USDC is a GRC20 stablecoin issued solely for testing purposes.",
    "website_url": "https://beta.gnoswap.io",
    "image": "/grc20/images/gno_land_r_demo_usdc.svg"
```

2024-05-27 06:00 UTC, jinoosss approved these changes
LGTM !

2024-05-27 06:01 UTC, r3v4s approved these changes

2024-05-27 06:02 UTC, merged